version: "3.8"
services:
  backend_news:
    image: app/ml-dev-int
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:9100"  
    networks: 
      - backend
    container_name: ml-dev-int-app
    depends_on: 
      - postgres
  postgres:
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"  
    networks: 
      - backend
    container_name: ml_servises_course
    volumes:
    - ./postgres-data:/var/lib/postgresql
networks:
  backend:
    driver: "bridge"

