version: "3.9"
services:
  backend:
    image: app/ml-dev-int
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    container_name: ml-dev-int-app
networks:
  dbproj_default:
    external: true