version: "3.9"
services:
  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"  
    container_name: ml_servises_course
    volumes:
    - ./postgres-data:/var/lib/postgresql